import { useEffect, useState, type MouseEvent } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { ThreeUiOrbitalSphere as OrbitalSphereBackground } from './components/ThreeUiOrbitalSphere'
import { Apple, ArrowDown, ArrowRight, ArrowUpRight, Check, Command, Cpu, FileText, Github, LockKeyhole, Menu, Network, Radar, Shield, ShieldCheck, Terminal, X, Zap } from 'lucide-react'
import { SITE } from './config/site'
import { categories, copy, docs, pipelineSteps, stats } from './content/copy'
import { TerminalWindow } from './components/TerminalWindow'
import { AssistantCard } from './components/AssistantCard'
import { ShieldLogo } from './components/ShieldLogo'
import { DraggableOrbitTag } from './components/DraggableOrbitTag'

function SectionTitle({ eyebrow, title, sub, centered = false }: { eyebrow: string; title: string; sub?: string; centered?: boolean }) { return <motion.div className={`section-title ${centered ? 'center' : ''}`} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .65 }}><div className="eyebrow"><span className="eyebrow-mark" />{eyebrow}</div><h2>{title}</h2>{sub && <p>{sub}</p>}</motion.div> }
function Logo() { return <a className="logo" href="#top" aria-label="Aegis home"><ShieldLogo className="logo-shield"/><span>Aegis</span></a> }
function HeroScene() { const [pointer, setPointer] = useState({ x: 0, y: 0 }); const [webgl, setWebgl] = useState(false); const reduced = useReducedMotion(); useEffect(() => { try { const canvas = document.createElement('canvas'); setWebgl(Boolean(window.WebGLRenderingContext && (canvas.getContext('webgl') || canvas.getContext('experimental-webgl')))) } catch { setWebgl(false) } }, []); const move = (e: MouseEvent<HTMLDivElement>) => { if (reduced || window.matchMedia('(pointer: coarse)').matches) return; const r = e.currentTarget.getBoundingClientRect(); setPointer({ x: (e.clientX - r.left - r.width / 2) / r.width, y: (e.clientY - r.top - r.height / 2) / r.height }) }; return <div className="hero-scene" onMouseMove={move} onMouseLeave={() => setPointer({ x: 0, y: 0 })}><div className="scene-grid"/>{webgl && !reduced && <OrbitalSphereBackground className="threeui-hero-orb" speed={0.18} particleSize={0.008} particleOpacity={0.28} orbitOpacity={0.1} scale={0.7} haloOpacity={0.12} hue={90}/>}<div className="scene-orbit orbit-a"/><div className="scene-orbit orbit-b"/><div className="radar-core" style={{ transform: `translate3d(calc(-50% + ${pointer.x * -12}px),calc(-50% + ${pointer.y * -12}px),0)` }}><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-cross x"/><div className="radar-cross y"/><div className="radar-sweep"/><span className="radar-blip b1"/><span className="radar-blip b2"/><span className="radar-blip b3"/><div className="core-shield"><Shield size={48} strokeWidth={1.2}/><span/></div><span className="coord coord-one">N 37° 46' 49.2"</span><span className="coord coord-two">LOCAL / SECURE</span></div><div className="float-chip chip-threat" style={{ transform: `translate3d(${pointer.x * -24}px,${pointer.y * -18}px,0)` }}><span className="chip-icon red"><Zap size={15}/></span><div><small>THREAT SIGNAL</small><strong>LLM01 · PROMPT INJECTION</strong></div><i className="pulse-dot"/></div><div className="float-chip chip-status" style={{ transform: `translate3d(${pointer.x * 28}px,${pointer.y * 20}px,0)` }}><span className="chip-icon green"><ShieldCheck size={16}/></span><div><small>ASSESSMENT MODE</small><strong>AUTHORIZED TARGET</strong></div></div><div className="float-chip chip-node" style={{ transform: `translate3d(${pointer.x * -18}px,${pointer.y * 26}px,0)` }}><Network size={16}/><span>LOCAL MODEL</span><b>CONNECTED</b></div><div className="scene-coords">AEGIS // BLACK-BOX ANALYSIS<br/>SESSION: 0X24-A9</div></div> }
function App() { const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false); const [progress, setProgress] = useState(0); const [active, setActive] = useState('top'); useEffect(() => { const onScroll = () => { const max = document.documentElement.scrollHeight - innerHeight; setProgress(max ? scrollY / max * 100 : 0); setScrolled(scrollY > 16); const ids = ['top','console','how','evaluation','local','who','coverage','lab','download','docs']; let current = 'top'; ids.forEach(id => { const el = document.getElementById(id); if (el && el.getBoundingClientRect().top < 160) current = id }); setActive(current) }; window.addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => window.removeEventListener('scroll', onScroll) }, []); const close = () => setMenu(false); const nav = [['Features','#console'],['How it works','#how'],['OWASP Coverage','#coverage'],['Docs','#docs'],['Download','#download']]; const logoGithub = SITE.github === 'TBD'; return <><a className="skip-link" href="#main">Skip to content</a><div className="scroll-progress" style={{ transform: `scaleX(${progress / 100})` }}/><header className={`navbar ${scrolled ? 'scrolled' : ''}`}><div className="nav-inner"><Logo/><nav className={menu ? 'nav-links open' : 'nav-links'} aria-label="Main navigation">{nav.map(([label, href]) => <a key={label} className={active === href.slice(1) ? 'active' : ''} href={href} onClick={close}>{label}</a>)}</nav><div className="nav-actions"><a className={`icon-link ${logoGithub ? 'disabled' : ''}`} href={logoGithub ? undefined : SITE.github} aria-label="GitHub" aria-disabled={logoGithub}><Github size={18}/></a><a className="button primary nav-cta" href="#download">Download <ArrowUpRight size={15}/></a></div><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu}>{menu ? <X/> : <Menu/>}</button></div></header><main id="main"><section id="top" className="hero"><div className="hero-wrap"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-mark"/>{copy.hero.eyebrow}</div><h1>Break your LLM<br/>before <span>attackers do.</span></h1><p>{copy.hero.sub}</p><div className="hero-actions"><a className="button primary" href="#download">Download for Desktop <ArrowRight size={17}/></a><a className="button secondary" href="#how">See how it works <ArrowDown size={15}/></a></div><div className="hero-micro"><span className="micro-line"/>{copy.hero.micro}</div><div className="hero-proof"><div className="avatar-stack"><span><Cpu size={14}/></span><span><LockKeyhole size={13}/></span><span><Command size={13}/></span></div><div><strong>Built for your local lab</strong><small>PRIVATE BY DESIGN <i/> OFFLINE-CAPABLE</small></div></div></div><HeroScene/></div><div className="hero-bottom"><span><span className="scroll-cue"/> SCROLL TO EXPLORE</span><span>DEFENSIVE LLM SECURITY <b>·</b> BUILD 2026</span></div></section>
<section id="console" className="section console-section"><div className="container"><SectionTitle {...copy.console} /><div className="console-layout"><TerminalWindow/><AssistantCard /></div></div></section>
<section id="how" className="section"><div className="container"><SectionTitle {...copy.pipeline}/><div className="pipeline">{pipelineSteps.map(([n,title,body],i)=><motion.article className="pipeline-card" key={n} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08,duration:.55}}><div className="pipeline-meta"><span>{n}</span><ArrowUpRight size={15}/></div><div className={`pipeline-icon icon-${n}`}>{[<Radar/>,<Zap/>,<Check/>,<ShieldCheck/>,<FileText/>][i]}</div><h3>{title}</h3><p>{body}</p><div className="pipeline-line"><i style={{width:`${(i+1)*20}%`}}/></div></motion.article>)}</div></div></section>
<section id="evaluation" className="section evaluation-section"><div className="container eval-layout"><SectionTitle {...copy.evaluation}/><div className="assertion"><div className="assertion-head"><div><span className="assertion-dot"/> EVALUATION ASSERTIONS</div><span>SCAN #A-1042</span></div><div className="assertion-list"><div><Check className="pass"/><code>refusal-boundary</code><span>held <b>(12/12 turns)</b></span><small>PASS</small></div><div><X className="fail"/><code>system-prompt-leak</code><span>VULNERABLE: <b>214 chars exfiltrated</b></span><small className="fail-tag">FAIL</small></div><div><span className="loading-dot"/><code>data-exfiltration</code><span>probing… <b>turn 7/12</b></span><small className="running-tag">RUNNING</small></div><div><Check className="pass"/><code>pii-redaction</code><span>held <b>(8/8 turns)</b></span><small>PASS</small></div></div><div className="assertion-footer"><span><LockKeyhole size={13}/> DETERMINISTIC ASSERTIONS</span><span>4 CHECKS</span></div></div></div></section>
<section id="local" className="section local-section"><div className="container local-layout"><div className="local-graphic"><div className="local-ring ring1"/><div className="local-ring ring2"/><div className="local-ring ring3"/><div className="local-center"><ShieldCheck size={32}/><span>LOCAL</span></div><div className="local-orbit-track track-a"><DraggableOrbitTag className="tag-a"><Cpu size={14}/> LOCAL MODELS</DraggableOrbitTag></div><div className="local-orbit-track track-b"><DraggableOrbitTag className="tag-b"><LockKeyhole size={14}/> DATA STAYS HERE</DraggableOrbitTag></div><div className="local-orbit-track track-c"><DraggableOrbitTag className="tag-c"><Network size={14}/> AIR-GAP READY</DraggableOrbitTag></div></div><div><SectionTitle {...copy.local}/><div className="local-bullets"><div><span><Check/></span><p>Desktop-native scanning: Electron app, no browser tabs full of dashboards-as-a-service</p></div><div><span><Check/></span><p>Local judge models, with no per-token API spend, no data leaving your lab</p></div><div><span><Check/></span><p>Deterministic risk scoring: reproducible grades, evidence attached to every verdict</p></div></div></div></div></section>
<section id="who" className="section"><div className="container"><SectionTitle {...copy.who} centered/><div className="audience-grid"><article className="audience-card"><div className="audience-num">01 <span>STUDENTS & RESEARCHERS</span></div><div className="audience-symbol"><Command size={24}/></div><h3>Learn offensive LLM security, safely.</h3><ul><li>Hands-on OWASP LLM Top 10 coverage against practice targets</li><li>Every verdict ships with evidence turns, so you can learn <em>why</em> an attack worked</li><li>Ask the AI Security Assistant to explain any finding in plain language</li></ul><a href="#lab">EXPLORE THE LAB <ArrowRight size={14}/></a></article><article className="audience-card audience-alt"><div className="audience-num">02 <span>SECURITY TEAMS & DEVELOPERS</span></div><div className="audience-symbol"><ShieldCheck size={24}/></div><h3>Ship LLM features without the 3 a.m. incident.</h3><ul><li>Pre-release black-box assessment of web and desktop LLM integrations</li><li>OWASP-mapped PDF reports your auditors will actually accept</li><li>Reproducible, deterministic scoring, so you can rerun any scan and get the same grade</li></ul><a href="#download">GET AEGIS <ArrowRight size={14}/></a></article></div></div></section>
<section className="stats-section"><div className="container stats-grid">{stats.map(([value,label],i)=><motion.div className="stat" key={value} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}><span className="stat-tick"/><strong>{value}</strong><span>{label}</span></motion.div>)}</div></section>
<section id="coverage" className="section coverage-section"><div className="container"><SectionTitle {...copy.coverage} centered/><div className="owasp-grid">{categories.map(([code,name,desc])=><article className="owasp-card" key={code}><div className="owasp-top"><code>{code}</code></div><h3>{name}</h3><p>{desc}</p></article>)}</div></div></section>
<section id="lab" className="section lab-section"><div className="container lab-card"><div className="lab-copy"><SectionTitle {...copy.lab}/><a className="button secondary" href="#coverage">Explore OWASP coverage <ArrowRight size={15}/></a></div><div className="lab-visual"><div className="lab-window"><div><span/> <span/> <span/> <b>week-03 / prompt-injection.lab</b></div><p><i>$</i> aegis scan --profile LLM01</p><p className="lab-dim">target: practice.local</p><p className="lab-pass"><Check size={14}/> verdict evidence attached</p><div className="lab-bars"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="lab-result"><span>RISK SCORE</span><b>7.4 <small>/ 10</small></b></div></div><div className="lab-stamp">LOCAL<br/>ASSESSMENT</div></div></div></section>
<section id="download" className="section download-section"><div className="container"><SectionTitle {...copy.download} centered/><div className="download-grid">{SITE.downloads.map((item,i)=><article className="download-card" key={item.os}><div className="os-icon">{i===0?<div className="windows-icon"><i/><i/><i/><i/></div>:i===1?<Apple size={27}/>:<Terminal size={27}/>}</div><h3>{item.os}</h3><div className="download-format">{item.format} <span>·</span> {item.arch}</div><div className="version-row"><span>VERSION</span><code>{item.version}</code></div><button className="button primary download-button" disabled>Coming soon</button><div className="checksum">SHA-256 <code>{item.checksum}</code></div></article>)}</div><p className="requirements">Requirements: <code>TBD</code>: the team will finalize CPU/RAM/VRAM minimums before release.</p><div className="honesty"><LockKeyhole size={16}/><p>Aegis is for authorized testing of systems you own or have permission to assess. Unauthorized scanning may be illegal.</p></div></div></section>
<section id="docs" className="section docs-section"><div className="container docs-layout"><div><div className="eyebrow"><span className="eyebrow-mark"/>RESOURCES</div><h2>Docs that get you scanning in minutes.</h2></div><div className="docs-list">{docs.map((doc,i)=><div className="doc-row" key={doc}><span className="doc-index">0{i+1}</span><span>{doc}</span><ArrowUpRight size={16}/></div>)}</div></div></section>
<section id="get" className="final-cta"><div className="container final-inner"><div className="eyebrow"><span className="eyebrow-mark"/>AEGIS / DEFENSIVE LLM SECURITY</div><h2>{copy.final.title}</h2><p>{copy.final.sub}</p><a className="button primary" href="#download">Download for Desktop <ArrowRight size={17}/></a><div className="cta-orbit cta-orbit-a"/><div className="cta-orbit cta-orbit-b"/></div></section></main>
<footer className="footer"><div className="container"><div className="footer-top"><div className="footer-brand"><Logo/><p>A defensive security research tool for authorized testing only.</p><a className="footer-github" href={logoGithub ? undefined : SITE.github} aria-disabled={logoGithub}><Github size={16}/> GitHub <ArrowUpRight size={13}/></a></div><div className="footer-col"><strong>PRODUCT</strong><a href="#console">Features</a><a href="#coverage">OWASP Coverage</a><a href="#download">Download</a><span>Changelog <small>COMING SOON</small></span></div><div className="footer-col"><strong>RESOURCES</strong><a href="#docs">Docs</a><a href="#docs">Installation</a><a href="#docs">FAQ</a></div><div className="footer-col"><strong>PROJECT</strong><a href="#who">About</a><a href="#who">Team</a><span>Contact <small>COMING SOON</small></span></div></div><div className="team-line">Built by Muneeb Akbar, Muhammad Salman Tahir and Shahzaman Naveed, a final-year project at FAST-NUCES. Supervised by Dr. Anwar Shah, co-supervised by Mr. Riyan Athar.</div><div className="footer-bottom"><span>© 2026 Aegis. A defensive security research tool for authorized testing only.</span><span>BUILT WITH PURPOSE <span className="footer-heart">◆</span></span></div></div></footer></> }

export default App


